FROM python:3.9-slim

WORKDIR /app

# Installer curl et autres dépendances système
RUN apt-get update && \
    apt-get install -y curl wget netcat-openbsd --no-install-recommends && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Installer les dépendances pour Selenium
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Créer un dossier pour les résultats des tests
RUN mkdir -p /app/test-outputs

# Copier le script d'attente et le rendre exécutable
COPY wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh

# Copier les scripts de test
COPY . .

# Copier le script de vérification des services et le rendre exécutable
COPY check-services.sh /check-services.sh
RUN chmod +x /check-services.sh

# Créer et copier le nouveau script watch-tests.sh
COPY watch-tests.sh /watch-tests.sh
RUN chmod +x /watch-tests.sh

# Utiliser le nouveau script qui garde le conteneur en vie
CMD ["sh", "watch-tests.sh"]
