FROM python:3.9-slim

WORKDIR /app

# Installer curl et autres dépendances système
RUN apt-get update && \
    apt-get install -y curl wget netcat-openbsd --no-install-recommends && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Installer les dépendances pour Selenium
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Créer un dossier pour les résultats des tests
RUN mkdir -p /app/tests/results

# Copier le script d'attente et le rendre exécutable
COPY wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh

# Copier les scripts de test
COPY . .

# Copier le script de vérification des services et le rendre exécutable
COPY check-services.sh /check-services.sh
RUN chmod +x /check-services.sh

# Par défaut, exécuter le script qui vérifie tous les services avant de lancer les tests
CMD ["sh", "check-services.sh"]
