services:
  # Surcharge de la configuration de la base de données pour les tests
  db:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app_db_test # Base de données spécifique aux tests

  # Surcharge du service front-back pour pointer vers la base de test
  front-back:
    environment:
      - NODE_ENV=test
      - DATABASE_URL=postgres://postgres:postgres@db:5432/app_db_test

  # Service Selenium pour les tests automatisés
  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
      - "7900:7900" # Port pour VNC Viewer (accès visuel aux tests)
    volumes:
      - /dev/shm:/dev/shm # Pour éviter les erreurs de mémoire
    environment:
      - SE_NODE_MAX_SESSIONS=5
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--spider",
          "--quiet",
          "http://localhost:4444/wd/hub/status",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Service pour exécuter les tests Selenium
  test-runner:
    build:
      context: ./front-back/tests
      dockerfile: dockerfile.test
    volumes:
      - ./front-back/tests:/app/tests
      - ./front-back/tests/test-outputs:/app/test-outputs
    depends_on:
      selenium:
        condition: service_healthy
      front-back:
        condition: service_healthy
    environment:
      - SELENIUM_REMOTE_URL=http://selenium:4444/wd/hub
      - APP_URL=http://front-back:3000
      - NODE_ENV=test
      - DATABASE_URL=postgres://postgres:postgres@db:5432/app_db_test # Ajout de la connexion à la base de test
