services:
    # Service PostgreSQL
  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app_db
     
  # Service frontend & backend Next.js
  front-back:
    build:
      context: ./front-back
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./front-back:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=postgres://postgres:postgres@db:5432/app_db

volumes:
  postgres_data: